name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker image
      run: docker build -t sasmik23/flask-app:latest .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push sasmik23/flask-app:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: v1.21.0

    - name: Configure kubectl
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config
        echo "Kubeconfig content:"
        cat $HOME/.kube/config
      env:
        KUBECONFIG: $HOME/.kube/config

    - name: List all contexts
      run: |
        echo "Available contexts:"
        kubectl config get-contexts
      env:
        KUBECONFIG: $HOME/.kube/config

    - name: Set kubectl context
      run: |
        kubectl config use-context iam-root-account@my-cluster.us-west-2.eksctl.io || echo "Context not found. Available contexts:" && kubectl config get-contexts
      env:
        KUBECONFIG: $HOME/.kube/config

    - name: Verify kubectl configuration
      run: |
        kubectl config view
        kubectl get nodes
      env:
        KUBECONFIG: $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
      env:
        KUBECONFIG: $HOME/.kube/config
